// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/raft.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VoteReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Term                 int64    `protobuf:"varint,2,opt,name=term" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteReq) Reset()         { *m = VoteReq{} }
func (m *VoteReq) String() string { return proto.CompactTextString(m) }
func (*VoteReq) ProtoMessage()    {}
func (*VoteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_42da5e25ff61d616, []int{0}
}
func (m *VoteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteReq.Unmarshal(m, b)
}
func (m *VoteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteReq.Marshal(b, m, deterministic)
}
func (dst *VoteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteReq.Merge(dst, src)
}
func (m *VoteReq) XXX_Size() int {
	return xxx_messageInfo_VoteReq.Size(m)
}
func (m *VoteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteReq.DiscardUnknown(m)
}

var xxx_messageInfo_VoteReq proto.InternalMessageInfo

func (m *VoteReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VoteReq) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

type VoteResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteResp) Reset()         { *m = VoteResp{} }
func (m *VoteResp) String() string { return proto.CompactTextString(m) }
func (*VoteResp) ProtoMessage()    {}
func (*VoteResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_42da5e25ff61d616, []int{1}
}
func (m *VoteResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteResp.Unmarshal(m, b)
}
func (m *VoteResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteResp.Marshal(b, m, deterministic)
}
func (dst *VoteResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteResp.Merge(dst, src)
}
func (m *VoteResp) XXX_Size() int {
	return xxx_messageInfo_VoteResp.Size(m)
}
func (m *VoteResp) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteResp.DiscardUnknown(m)
}

var xxx_messageInfo_VoteResp proto.InternalMessageInfo

type HeartBeatReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	LastCommit           int64    `protobuf:"varint,2,opt,name=lastCommit" json:"lastCommit,omitempty"`
	Term                 int64    `protobuf:"varint,3,opt,name=term" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatReq) Reset()         { *m = HeartBeatReq{} }
func (m *HeartBeatReq) String() string { return proto.CompactTextString(m) }
func (*HeartBeatReq) ProtoMessage()    {}
func (*HeartBeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_42da5e25ff61d616, []int{2}
}
func (m *HeartBeatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatReq.Unmarshal(m, b)
}
func (m *HeartBeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatReq.Marshal(b, m, deterministic)
}
func (dst *HeartBeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatReq.Merge(dst, src)
}
func (m *HeartBeatReq) XXX_Size() int {
	return xxx_messageInfo_HeartBeatReq.Size(m)
}
func (m *HeartBeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatReq proto.InternalMessageInfo

func (m *HeartBeatReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HeartBeatReq) GetLastCommit() int64 {
	if m != nil {
		return m.LastCommit
	}
	return 0
}

func (m *HeartBeatReq) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

type HeartBeatResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatResp) Reset()         { *m = HeartBeatResp{} }
func (m *HeartBeatResp) String() string { return proto.CompactTextString(m) }
func (*HeartBeatResp) ProtoMessage()    {}
func (*HeartBeatResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_42da5e25ff61d616, []int{3}
}
func (m *HeartBeatResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatResp.Unmarshal(m, b)
}
func (m *HeartBeatResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatResp.Marshal(b, m, deterministic)
}
func (dst *HeartBeatResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatResp.Merge(dst, src)
}
func (m *HeartBeatResp) XXX_Size() int {
	return xxx_messageInfo_HeartBeatResp.Size(m)
}
func (m *HeartBeatResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatResp.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatResp proto.InternalMessageInfo

type Entry struct {
	Command              string   `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	Index                int64    `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	Term                 int64    `protobuf:"varint,3,opt,name=term" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_42da5e25ff61d616, []int{4}
}
func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (dst *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(dst, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Entry) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Entry) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

type AppendEntryReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	LastCommit           int64    `protobuf:"varint,2,opt,name=lastCommit" json:"lastCommit,omitempty"`
	PreIndex             int64    `protobuf:"varint,3,opt,name=preIndex" json:"preIndex,omitempty"`
	PreTerm              int64    `protobuf:"varint,4,opt,name=preTerm" json:"preTerm,omitempty"`
	Term                 int64    `protobuf:"varint,5,opt,name=term" json:"term,omitempty"`
	Entries              []*Entry `protobuf:"bytes,6,rep,name=entries" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntryReq) Reset()         { *m = AppendEntryReq{} }
func (m *AppendEntryReq) String() string { return proto.CompactTextString(m) }
func (*AppendEntryReq) ProtoMessage()    {}
func (*AppendEntryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_42da5e25ff61d616, []int{5}
}
func (m *AppendEntryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntryReq.Unmarshal(m, b)
}
func (m *AppendEntryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntryReq.Marshal(b, m, deterministic)
}
func (dst *AppendEntryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntryReq.Merge(dst, src)
}
func (m *AppendEntryReq) XXX_Size() int {
	return xxx_messageInfo_AppendEntryReq.Size(m)
}
func (m *AppendEntryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntryReq.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntryReq proto.InternalMessageInfo

func (m *AppendEntryReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AppendEntryReq) GetLastCommit() int64 {
	if m != nil {
		return m.LastCommit
	}
	return 0
}

func (m *AppendEntryReq) GetPreIndex() int64 {
	if m != nil {
		return m.PreIndex
	}
	return 0
}

func (m *AppendEntryReq) GetPreTerm() int64 {
	if m != nil {
		return m.PreTerm
	}
	return 0
}

func (m *AppendEntryReq) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntryReq) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type AppendEntryResp struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntryResp) Reset()         { *m = AppendEntryResp{} }
func (m *AppendEntryResp) String() string { return proto.CompactTextString(m) }
func (*AppendEntryResp) ProtoMessage()    {}
func (*AppendEntryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_42da5e25ff61d616, []int{6}
}
func (m *AppendEntryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntryResp.Unmarshal(m, b)
}
func (m *AppendEntryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntryResp.Marshal(b, m, deterministic)
}
func (dst *AppendEntryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntryResp.Merge(dst, src)
}
func (m *AppendEntryResp) XXX_Size() int {
	return xxx_messageInfo_AppendEntryResp.Size(m)
}
func (m *AppendEntryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntryResp.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntryResp proto.InternalMessageInfo

func (m *AppendEntryResp) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*VoteReq)(nil), "proto.VoteReq")
	proto.RegisterType((*VoteResp)(nil), "proto.VoteResp")
	proto.RegisterType((*HeartBeatReq)(nil), "proto.HeartBeatReq")
	proto.RegisterType((*HeartBeatResp)(nil), "proto.HeartBeatResp")
	proto.RegisterType((*Entry)(nil), "proto.Entry")
	proto.RegisterType((*AppendEntryReq)(nil), "proto.AppendEntryReq")
	proto.RegisterType((*AppendEntryResp)(nil), "proto.AppendEntryResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Raft service

type RaftClient interface {
	AppendEntry(ctx context.Context, in *AppendEntryReq, opts ...grpc.CallOption) (*AppendEntryResp, error)
	HeartBeat(ctx context.Context, in *HeartBeatReq, opts ...grpc.CallOption) (*HeartBeatResp, error)
	Vote(ctx context.Context, in *VoteReq, opts ...grpc.CallOption) (*VoteResp, error)
}

type raftClient struct {
	cc *grpc.ClientConn
}

func NewRaftClient(cc *grpc.ClientConn) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) AppendEntry(ctx context.Context, in *AppendEntryReq, opts ...grpc.CallOption) (*AppendEntryResp, error) {
	out := new(AppendEntryResp)
	err := grpc.Invoke(ctx, "/proto.Raft/AppendEntry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) HeartBeat(ctx context.Context, in *HeartBeatReq, opts ...grpc.CallOption) (*HeartBeatResp, error) {
	out := new(HeartBeatResp)
	err := grpc.Invoke(ctx, "/proto.Raft/HeartBeat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) Vote(ctx context.Context, in *VoteReq, opts ...grpc.CallOption) (*VoteResp, error) {
	out := new(VoteResp)
	err := grpc.Invoke(ctx, "/proto.Raft/Vote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Raft service

type RaftServer interface {
	AppendEntry(context.Context, *AppendEntryReq) (*AppendEntryResp, error)
	HeartBeat(context.Context, *HeartBeatReq) (*HeartBeatResp, error)
	Vote(context.Context, *VoteReq) (*VoteResp, error)
}

func RegisterRaftServer(s *grpc.Server, srv RaftServer) {
	s.RegisterService(&_Raft_serviceDesc, srv)
}

func _Raft_AppendEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).AppendEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Raft/AppendEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).AppendEntry(ctx, req.(*AppendEntryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartBeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Raft/HeartBeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).HeartBeat(ctx, req.(*HeartBeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_Vote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).Vote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Raft/Vote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).Vote(ctx, req.(*VoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Raft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntry",
			Handler:    _Raft_AppendEntry_Handler,
		},
		{
			MethodName: "HeartBeat",
			Handler:    _Raft_HeartBeat_Handler,
		},
		{
			MethodName: "Vote",
			Handler:    _Raft_Vote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/raft.proto",
}

func init() { proto.RegisterFile("proto/raft.proto", fileDescriptor_raft_42da5e25ff61d616) }

var fileDescriptor_raft_42da5e25ff61d616 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x49, 0x9a, 0xf4, 0xcf, 0xb5, 0xb4, 0xe8, 0x28, 0x28, 0xca, 0x80, 0x8a, 0x07, 0x54,
	0x06, 0x8a, 0x54, 0x16, 0x26, 0x24, 0x40, 0x48, 0x20, 0x36, 0x0b, 0xb1, 0x1b, 0xe2, 0x4a, 0x51,
	0x49, 0x6c, 0x6c, 0x0f, 0xf0, 0x99, 0xd8, 0xf8, 0x84, 0x28, 0xb6, 0x1b, 0x52, 0x91, 0x89, 0x29,
	0x7e, 0xef, 0xce, 0xef, 0x7e, 0xb1, 0x0d, 0x7b, 0x52, 0x09, 0x23, 0xce, 0x15, 0x5b, 0x99, 0x85,
	0x5d, 0x62, 0x6c, 0x3f, 0xe4, 0x0c, 0x7a, 0xcf, 0xc2, 0x70, 0xca, 0xdf, 0x71, 0x0c, 0x61, 0x9e,
	0x25, 0xc1, 0x2c, 0x98, 0x77, 0x68, 0x98, 0x67, 0x88, 0x10, 0x19, 0xae, 0x8a, 0x24, 0xb4, 0x8e,
	0x5d, 0x13, 0x80, 0xbe, 0x6b, 0xd7, 0x92, 0x50, 0x18, 0xdd, 0x73, 0xa6, 0xcc, 0x0d, 0x67, 0xa6,
	0x6d, 0xff, 0x11, 0xc0, 0x1b, 0xd3, 0xe6, 0x56, 0x14, 0x45, 0x6e, 0x7c, 0x4a, 0xc3, 0xa9, 0xf3,
	0x3b, 0x8d, 0xfc, 0x09, 0xec, 0x36, 0x32, 0xb5, 0x24, 0x8f, 0x10, 0xdf, 0x95, 0x46, 0x7d, 0x62,
	0x02, 0xbd, 0x57, 0x51, 0x14, 0xac, 0x74, 0x23, 0x06, 0x74, 0x23, 0x71, 0x0a, 0x71, 0x5e, 0x66,
	0xfc, 0xc3, 0x8f, 0x70, 0xa2, 0x35, 0xfd, 0x3b, 0x80, 0xf1, 0xb5, 0x94, 0xbc, 0xcc, 0x6c, 0xe6,
	0x7f, 0xa0, 0x53, 0xe8, 0x4b, 0xc5, 0x1f, 0xec, 0x3c, 0x17, 0x5d, 0xeb, 0x0a, 0x51, 0x2a, 0xfe,
	0x54, 0x4d, 0x8d, 0x6c, 0x69, 0x23, 0x6b, 0x98, 0xf8, 0x17, 0x06, 0x4f, 0xa0, 0xc7, 0x4b, 0xa3,
	0x72, 0xae, 0x93, 0xee, 0xac, 0x33, 0x1f, 0x2e, 0x47, 0xee, 0x66, 0x16, 0x8e, 0x6d, 0x53, 0x24,
	0xc7, 0x30, 0xd9, 0x62, 0xd6, 0xb2, 0x82, 0x16, 0x6b, 0x0b, 0xdd, 0xa7, 0xa1, 0x58, 0x2f, 0xbf,
	0x02, 0x88, 0x28, 0x5b, 0x19, 0xbc, 0x82, 0x61, 0xa3, 0x17, 0x0f, 0x7c, 0xe2, 0xf6, 0x3f, 0xa7,
	0x87, 0x6d, 0xb6, 0x96, 0x64, 0x07, 0x2f, 0x61, 0x50, 0x1f, 0x3f, 0xee, 0xfb, 0xb6, 0xe6, 0x25,
	0xa7, 0xd3, 0xbf, 0xa6, 0xdd, 0x79, 0x0a, 0x51, 0xf5, 0x30, 0x70, 0xec, 0xeb, 0xfe, 0x51, 0xa5,
	0x93, 0x2d, 0x5d, 0xb5, 0xbe, 0x74, 0xad, 0x73, 0xf1, 0x13, 0x00, 0x00, 0xff, 0xff, 0x66, 0x54,
	0x8d, 0x89, 0x94, 0x02, 0x00, 0x00,
}
