// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/raft.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VoteReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Term                 int64    `protobuf:"varint,2,opt,name=term" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteReq) Reset()         { *m = VoteReq{} }
func (m *VoteReq) String() string { return proto.CompactTextString(m) }
func (*VoteReq) ProtoMessage()    {}
func (*VoteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_2838cf1eb76a6d31, []int{0}
}
func (m *VoteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteReq.Unmarshal(m, b)
}
func (m *VoteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteReq.Marshal(b, m, deterministic)
}
func (dst *VoteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteReq.Merge(dst, src)
}
func (m *VoteReq) XXX_Size() int {
	return xxx_messageInfo_VoteReq.Size(m)
}
func (m *VoteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteReq.DiscardUnknown(m)
}

var xxx_messageInfo_VoteReq proto.InternalMessageInfo

func (m *VoteReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VoteReq) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

type VoteResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteResp) Reset()         { *m = VoteResp{} }
func (m *VoteResp) String() string { return proto.CompactTextString(m) }
func (*VoteResp) ProtoMessage()    {}
func (*VoteResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_2838cf1eb76a6d31, []int{1}
}
func (m *VoteResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteResp.Unmarshal(m, b)
}
func (m *VoteResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteResp.Marshal(b, m, deterministic)
}
func (dst *VoteResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteResp.Merge(dst, src)
}
func (m *VoteResp) XXX_Size() int {
	return xxx_messageInfo_VoteResp.Size(m)
}
func (m *VoteResp) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteResp.DiscardUnknown(m)
}

var xxx_messageInfo_VoteResp proto.InternalMessageInfo

type HeartBeatReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	LastCommit           int64    `protobuf:"varint,2,opt,name=lastCommit" json:"lastCommit,omitempty"`
	Term                 int64    `protobuf:"varint,3,opt,name=term" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatReq) Reset()         { *m = HeartBeatReq{} }
func (m *HeartBeatReq) String() string { return proto.CompactTextString(m) }
func (*HeartBeatReq) ProtoMessage()    {}
func (*HeartBeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_2838cf1eb76a6d31, []int{2}
}
func (m *HeartBeatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatReq.Unmarshal(m, b)
}
func (m *HeartBeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatReq.Marshal(b, m, deterministic)
}
func (dst *HeartBeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatReq.Merge(dst, src)
}
func (m *HeartBeatReq) XXX_Size() int {
	return xxx_messageInfo_HeartBeatReq.Size(m)
}
func (m *HeartBeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatReq proto.InternalMessageInfo

func (m *HeartBeatReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HeartBeatReq) GetLastCommit() int64 {
	if m != nil {
		return m.LastCommit
	}
	return 0
}

func (m *HeartBeatReq) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

type HeartBeatResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatResp) Reset()         { *m = HeartBeatResp{} }
func (m *HeartBeatResp) String() string { return proto.CompactTextString(m) }
func (*HeartBeatResp) ProtoMessage()    {}
func (*HeartBeatResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_2838cf1eb76a6d31, []int{3}
}
func (m *HeartBeatResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatResp.Unmarshal(m, b)
}
func (m *HeartBeatResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatResp.Marshal(b, m, deterministic)
}
func (dst *HeartBeatResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatResp.Merge(dst, src)
}
func (m *HeartBeatResp) XXX_Size() int {
	return xxx_messageInfo_HeartBeatResp.Size(m)
}
func (m *HeartBeatResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatResp.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatResp proto.InternalMessageInfo

type Entry struct {
	Command              string   `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	Index                int64    `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	Term                 int64    `protobuf:"varint,4,opt,name=term" json:"term,omitempty"`
	Value                string   `protobuf:"bytes,5,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_2838cf1eb76a6d31, []int{4}
}
func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (dst *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(dst, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Entry) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Entry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Entry) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Entry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AppendEntryReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	LastCommit           int64    `protobuf:"varint,2,opt,name=lastCommit" json:"lastCommit,omitempty"`
	PreIndex             int64    `protobuf:"varint,3,opt,name=preIndex" json:"preIndex,omitempty"`
	PreTerm              int64    `protobuf:"varint,4,opt,name=preTerm" json:"preTerm,omitempty"`
	Term                 int64    `protobuf:"varint,5,opt,name=term" json:"term,omitempty"`
	Entries              []*Entry `protobuf:"bytes,6,rep,name=entries" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntryReq) Reset()         { *m = AppendEntryReq{} }
func (m *AppendEntryReq) String() string { return proto.CompactTextString(m) }
func (*AppendEntryReq) ProtoMessage()    {}
func (*AppendEntryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_2838cf1eb76a6d31, []int{5}
}
func (m *AppendEntryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntryReq.Unmarshal(m, b)
}
func (m *AppendEntryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntryReq.Marshal(b, m, deterministic)
}
func (dst *AppendEntryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntryReq.Merge(dst, src)
}
func (m *AppendEntryReq) XXX_Size() int {
	return xxx_messageInfo_AppendEntryReq.Size(m)
}
func (m *AppendEntryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntryReq.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntryReq proto.InternalMessageInfo

func (m *AppendEntryReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AppendEntryReq) GetLastCommit() int64 {
	if m != nil {
		return m.LastCommit
	}
	return 0
}

func (m *AppendEntryReq) GetPreIndex() int64 {
	if m != nil {
		return m.PreIndex
	}
	return 0
}

func (m *AppendEntryReq) GetPreTerm() int64 {
	if m != nil {
		return m.PreTerm
	}
	return 0
}

func (m *AppendEntryReq) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntryReq) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type AppendEntryResp struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntryResp) Reset()         { *m = AppendEntryResp{} }
func (m *AppendEntryResp) String() string { return proto.CompactTextString(m) }
func (*AppendEntryResp) ProtoMessage()    {}
func (*AppendEntryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_2838cf1eb76a6d31, []int{6}
}
func (m *AppendEntryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntryResp.Unmarshal(m, b)
}
func (m *AppendEntryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntryResp.Marshal(b, m, deterministic)
}
func (dst *AppendEntryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntryResp.Merge(dst, src)
}
func (m *AppendEntryResp) XXX_Size() int {
	return xxx_messageInfo_AppendEntryResp.Size(m)
}
func (m *AppendEntryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntryResp.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntryResp proto.InternalMessageInfo

func (m *AppendEntryResp) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type PutReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutReq) Reset()         { *m = PutReq{} }
func (m *PutReq) String() string { return proto.CompactTextString(m) }
func (*PutReq) ProtoMessage()    {}
func (*PutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_2838cf1eb76a6d31, []int{7}
}
func (m *PutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutReq.Unmarshal(m, b)
}
func (m *PutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutReq.Marshal(b, m, deterministic)
}
func (dst *PutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutReq.Merge(dst, src)
}
func (m *PutReq) XXX_Size() int {
	return xxx_messageInfo_PutReq.Size(m)
}
func (m *PutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PutReq.DiscardUnknown(m)
}

var xxx_messageInfo_PutReq proto.InternalMessageInfo

func (m *PutReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutReq) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PutResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResp) Reset()         { *m = PutResp{} }
func (m *PutResp) String() string { return proto.CompactTextString(m) }
func (*PutResp) ProtoMessage()    {}
func (*PutResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_2838cf1eb76a6d31, []int{8}
}
func (m *PutResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResp.Unmarshal(m, b)
}
func (m *PutResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResp.Marshal(b, m, deterministic)
}
func (dst *PutResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResp.Merge(dst, src)
}
func (m *PutResp) XXX_Size() int {
	return xxx_messageInfo_PutResp.Size(m)
}
func (m *PutResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResp.DiscardUnknown(m)
}

var xxx_messageInfo_PutResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*VoteReq)(nil), "proto.VoteReq")
	proto.RegisterType((*VoteResp)(nil), "proto.VoteResp")
	proto.RegisterType((*HeartBeatReq)(nil), "proto.HeartBeatReq")
	proto.RegisterType((*HeartBeatResp)(nil), "proto.HeartBeatResp")
	proto.RegisterType((*Entry)(nil), "proto.Entry")
	proto.RegisterType((*AppendEntryReq)(nil), "proto.AppendEntryReq")
	proto.RegisterType((*AppendEntryResp)(nil), "proto.AppendEntryResp")
	proto.RegisterType((*PutReq)(nil), "proto.PutReq")
	proto.RegisterType((*PutResp)(nil), "proto.PutResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Replica service

type ReplicaClient interface {
	AppendEntry(ctx context.Context, in *AppendEntryReq, opts ...grpc.CallOption) (*AppendEntryResp, error)
	HeartBeat(ctx context.Context, in *HeartBeatReq, opts ...grpc.CallOption) (*HeartBeatResp, error)
	Vote(ctx context.Context, in *VoteReq, opts ...grpc.CallOption) (*VoteResp, error)
}

type replicaClient struct {
	cc *grpc.ClientConn
}

func NewReplicaClient(cc *grpc.ClientConn) ReplicaClient {
	return &replicaClient{cc}
}

func (c *replicaClient) AppendEntry(ctx context.Context, in *AppendEntryReq, opts ...grpc.CallOption) (*AppendEntryResp, error) {
	out := new(AppendEntryResp)
	err := grpc.Invoke(ctx, "/proto.Replica/AppendEntry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaClient) HeartBeat(ctx context.Context, in *HeartBeatReq, opts ...grpc.CallOption) (*HeartBeatResp, error) {
	out := new(HeartBeatResp)
	err := grpc.Invoke(ctx, "/proto.Replica/HeartBeat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaClient) Vote(ctx context.Context, in *VoteReq, opts ...grpc.CallOption) (*VoteResp, error) {
	out := new(VoteResp)
	err := grpc.Invoke(ctx, "/proto.Replica/Vote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Replica service

type ReplicaServer interface {
	AppendEntry(context.Context, *AppendEntryReq) (*AppendEntryResp, error)
	HeartBeat(context.Context, *HeartBeatReq) (*HeartBeatResp, error)
	Vote(context.Context, *VoteReq) (*VoteResp, error)
}

func RegisterReplicaServer(s *grpc.Server, srv ReplicaServer) {
	s.RegisterService(&_Replica_serviceDesc, srv)
}

func _Replica_AppendEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServer).AppendEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Replica/AppendEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServer).AppendEntry(ctx, req.(*AppendEntryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replica_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartBeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Replica/HeartBeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServer).HeartBeat(ctx, req.(*HeartBeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replica_Vote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServer).Vote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Replica/Vote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServer).Vote(ctx, req.(*VoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Replica_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Replica",
	HandlerType: (*ReplicaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntry",
			Handler:    _Replica_AppendEntry_Handler,
		},
		{
			MethodName: "HeartBeat",
			Handler:    _Replica_HeartBeat_Handler,
		},
		{
			MethodName: "Vote",
			Handler:    _Replica_Vote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/raft.proto",
}

// Client API for Raft service

type RaftClient interface {
	Put(ctx context.Context, in *PutReq, opts ...grpc.CallOption) (*PutResp, error)
}

type raftClient struct {
	cc *grpc.ClientConn
}

func NewRaftClient(cc *grpc.ClientConn) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) Put(ctx context.Context, in *PutReq, opts ...grpc.CallOption) (*PutResp, error) {
	out := new(PutResp)
	err := grpc.Invoke(ctx, "/proto.Raft/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Raft service

type RaftServer interface {
	Put(context.Context, *PutReq) (*PutResp, error)
}

func RegisterRaftServer(s *grpc.Server, srv RaftServer) {
	s.RegisterService(&_Raft_serviceDesc, srv)
}

func _Raft_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Raft/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).Put(ctx, req.(*PutReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Raft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _Raft_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/raft.proto",
}

func init() { proto.RegisterFile("proto/raft.proto", fileDescriptor_raft_2838cf1eb76a6d31) }

var fileDescriptor_raft_2838cf1eb76a6d31 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x8f, 0xda, 0x30,
	0x10, 0x6d, 0xbe, 0x08, 0x19, 0x20, 0x20, 0x97, 0x56, 0x51, 0x0e, 0x15, 0xf5, 0x01, 0xd1, 0x43,
	0x69, 0x45, 0x2f, 0x3d, 0x55, 0x6a, 0xab, 0x4a, 0xed, 0x0d, 0x59, 0xd5, 0xde, 0xbd, 0xc4, 0x48,
	0x11, 0x24, 0xf1, 0xda, 0x66, 0xb5, 0xfc, 0xa9, 0x3d, 0xec, 0x2f, 0x5c, 0xc5, 0x36, 0xc1, 0x68,
	0x39, 0xed, 0x29, 0x7e, 0x93, 0x37, 0xf3, 0x9e, 0x9f, 0x07, 0x26, 0x5c, 0x34, 0xaa, 0xf9, 0x22,
	0xe8, 0x56, 0x2d, 0xf5, 0x11, 0x45, 0xfa, 0x83, 0x3f, 0x43, 0x7c, 0xd3, 0x28, 0x46, 0xd8, 0x1d,
	0x4a, 0xc1, 0x2f, 0x8b, 0xcc, 0x9b, 0x79, 0x8b, 0x80, 0xf8, 0x65, 0x81, 0x10, 0x84, 0x8a, 0x89,
	0x2a, 0xf3, 0x75, 0x45, 0x9f, 0x31, 0x40, 0xdf, 0xd0, 0x25, 0xc7, 0x04, 0x86, 0x7f, 0x19, 0x15,
	0xea, 0x17, 0xa3, 0xea, 0x5a, 0xff, 0x07, 0x80, 0x3d, 0x95, 0xea, 0x77, 0x53, 0x55, 0xa5, 0xb2,
	0x53, 0x9c, 0x4a, 0x37, 0x3f, 0x70, 0xe6, 0x8f, 0x61, 0xe4, 0xcc, 0x94, 0x1c, 0x4b, 0x88, 0xfe,
	0xd4, 0x4a, 0x1c, 0x51, 0x06, 0xf1, 0xa6, 0xa9, 0x2a, 0x5a, 0x1b, 0x89, 0x84, 0x9c, 0x20, 0x9a,
	0x42, 0x54, 0xd6, 0x05, 0x7b, 0xb0, 0x12, 0x06, 0xa0, 0x09, 0x04, 0x3b, 0x76, 0xd4, 0xc3, 0x13,
	0xd2, 0x1e, 0x3b, 0xbd, 0xf0, 0xac, 0xd7, 0xf6, 0xde, 0xd3, 0xfd, 0x81, 0x65, 0x91, 0xe6, 0x19,
	0x80, 0x9f, 0x3c, 0x48, 0x7f, 0x72, 0xce, 0xea, 0x42, 0x6b, 0xbf, 0xe6, 0x72, 0x39, 0xf4, 0xb9,
	0x60, 0xff, 0xb4, 0x2f, 0x73, 0xc1, 0x0e, 0xb7, 0x57, 0xe1, 0x82, 0xfd, 0x3f, 0x7b, 0x39, 0xc1,
	0xce, 0x62, 0xe4, 0x58, 0x9c, 0x43, 0xcc, 0x6a, 0x25, 0x4a, 0x26, 0xb3, 0xde, 0x2c, 0x58, 0x0c,
	0x56, 0x43, 0xf3, 0x82, 0x4b, 0xe3, 0xed, 0xf4, 0x13, 0x7f, 0x84, 0xf1, 0x85, 0x67, 0xc9, 0x5b,
	0xd3, 0xcd, 0x4e, 0x9b, 0xee, 0x13, 0xbf, 0xd9, 0xe1, 0xaf, 0xd0, 0x5b, 0x1f, 0xf4, 0x5b, 0xd9,
	0x74, 0xbc, 0x73, 0x3a, 0x5d, 0x12, 0xbe, 0x9b, 0x44, 0x02, 0xb1, 0xee, 0x90, 0x7c, 0xf5, 0xe8,
	0x41, 0x4c, 0x18, 0xdf, 0x97, 0x1b, 0x8a, 0x7e, 0xc0, 0xc0, 0xd1, 0x42, 0xef, 0xac, 0xa3, 0xcb,
	0xcc, 0xf2, 0xf7, 0xd7, 0xca, 0x92, 0xe3, 0x37, 0xe8, 0x3b, 0x24, 0xdd, 0x33, 0xa3, 0xb7, 0x96,
	0xe6, 0x2e, 0x53, 0x3e, 0x7d, 0x59, 0xd4, 0x9d, 0x9f, 0x20, 0x6c, 0x17, 0x10, 0xa5, 0xf6, 0xbf,
	0x5d, 0xde, 0x7c, 0x7c, 0x81, 0x5b, 0xea, 0x6a, 0x09, 0x21, 0xa1, 0x5b, 0x85, 0xe6, 0x10, 0xac,
	0x0f, 0x0a, 0x8d, 0x2c, 0xc3, 0x24, 0x90, 0xa7, 0x2e, 0x6c, 0xf9, 0xb7, 0x3d, 0x5d, 0xf8, 0xf6,
	0x1c, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x49, 0x71, 0x61, 0x2c, 0x03, 0x00, 0x00,
}
